const classes = [
  {
    index: 1,
    label: 'Aula 1',
    type: 'class',
    date: 'SEG - 19/07',
    videoId: 'bOxWmi-43GI',
    title: 'Oportunidades da Caligrafia',
    locked: false,
  },
  {
    index: 2,
    label: 'Live',
    type: 'live',
    date: 'TER - 20/07',
    videoId: '_qyX41Rg_ls',
    title: 'Live Tira-Dúvidas',
    locked: true,
  },
  {
    index: 3,
    label: 'Aula 2',
    type: 'class',
    date: 'QUA - 21/07',
    videoId: 'AxAMtgFXQ-s',
    title: '5 Passos para começar na Caligrafia',
    locked: true,
  },
  {
    index: 4,
    label: 'Live',
    type: 'live',
    date: 'QUI - 22/07',
    videoId: 'HYfcWQiLhIg',
    title: 'Live Tira-Dúvidas',
    locked: true,
  },
  {
    index: 5,
    label: 'Aula 3',
    type: 'class',
    date: 'SEX - 23/07',
    videoId: 'soVmlWRDFM0',
    title: 'Transformando letras em arte',
    locked: true,
  },
  {
    index: 6,
    label: 'Live',
    type: 'live',
    date: 'SÁB - 24/07',
    videoId: '9yqdmgsthqY',
    title: 'Live Tira-Dúvidas',
    locked: true,
  },
]

export default classes
