const groups = {
  1: 'https://chat.whatsapp.com/EEoEADuaLLNDviFIJwWQ1L',
  2: 'https://chat.whatsapp.com/EYW7DJQYH8MFFldWfLKXOg',
  3: 'https://chat.whatsapp.com/IsOX8KI0l7RBFNiAy5ctx4',
  4: 'https://chat.whatsapp.com/BaUBFEvPb9w6fIBsIumJd1',
  5: 'https://chat.whatsapp.com/Jr4PrI2XaGb0pg42vQkwuB',
  6: 'https://chat.whatsapp.com/Ex5rD17xGkLDbxlnfS1VCF',
  7: 'https://chat.whatsapp.com/CQ4eds9fGDiEMbUOlKUgni',
  8: 'https://chat.whatsapp.com/DfSpOsxGs797C84r1yDrzF',
  9: 'https://chat.whatsapp.com/JwOb0MP9oid1VXliXoqqyz',
  10: 'https://chat.whatsapp.com/F8rAAf4Kksz764pjmxLbm1',
  11: 'https://chat.whatsapp.com/HF2oyrnbeXe6xGIw9S17Pk',
  12: 'https://chat.whatsapp.com/H0FdifW8zA41XlTtTG3Van',
  13: 'https://chat.whatsapp.com/EusA3NTHhyi263Ejriisew',
  14: 'https://chat.whatsapp.com/HEas6qRrXPLD8iLLRgSN7J',
  15: 'https://chat.whatsapp.com/BhjM4Nc90AqJ65oD8K6yHv',
  16: 'https://chat.whatsapp.com/CBkOA8xBeC28kJIuGmr5c8',
  17: 'https://chat.whatsapp.com/DcaGUDe8o4C3zG1xpiLybJ',
  18: 'https://chat.whatsapp.com/JNruaMQQ4axIQyRW1O6CgX',
  19: 'https://chat.whatsapp.com/Js8t1ClEPuL51VNflqzPNf',
  20: 'https://chat.whatsapp.com/C0CdMd7UEzhLvEihcvHohI',
  21: 'https://chat.whatsapp.com/LK7QmZyJOxo9feB3r9LNrE',
  22: 'https://chat.whatsapp.com/BWqr4kYa8EN6ZeH27j3t6B',
  23: 'https://chat.whatsapp.com/LO2hqSs6dp764YjZ2mOxcP',
  24: 'https://chat.whatsapp.com/KPfkI2nKqZmFJEc27bHhH2',
  25: 'https://chat.whatsapp.com/EXdFYzWXh2C5ZCFzBqH2Mp',
  26: 'https://chat.whatsapp.com/HgKYHw8dUFa131z8L8RaQi',
  27: 'https://chat.whatsapp.com/DhdQeMhKZWeACzr4c90kdT',
  28: 'https://chat.whatsapp.com/KG4iVtjicXLDX3FrmhjUkZ',
  29: 'https://chat.whatsapp.com/CZsnQO9CC9jEZoQ2ldAbPY',
  30: 'https://chat.whatsapp.com/BepPdjMBwyNFvFUfxk8bDv',
  31: 'https://chat.whatsapp.com/DRkuSK1XDc7HoVnZmVxebh',
  32: 'https://chat.whatsapp.com/Bl5lJDDdbcE10gaBh41cAt',
  33: 'https://chat.whatsapp.com/Hc5DHFHYXaG6ss7bnQtA84',
  34: 'https://chat.whatsapp.com/KlWfxZUBhFGF5NFQLQIuHB',
  35: 'https://chat.whatsapp.com/JzyB6HiUM6g6yGowN4jUB1',
  36: 'https://chat.whatsapp.com/K1W897MkkEQJglLsS6vX4K',
  37: 'https://chat.whatsapp.com/LiVKkiJs6IvKhvFbeCUmou',
  38: 'https://chat.whatsapp.com/HkS9sCIW50q6sKzqWaIeS5',
  39: 'https://chat.whatsapp.com/HoHIkyUX3F8IgdH1Ck0et8',
}

export default groups
